version: 0.0 # CodeDeploy 버전
os: linux
files:
  - source: / # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상 지정: 루트 경로(전체 파일)
    destination: /home/ubuntu/deploytest
    overwrite: yes
hooks:
  AfterInstall:
    - location: ~/scripts/deploy.sh
      timeout: 60
      runas: ubuntu
