spring:
  application:
    name: mygithubprac

  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common

server:
  env: blue


---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 43.203.63.159

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  serverAddress: 43.203.63.159

serverName: green_server


---

spring:
  config:
    activate:
      on-profile: common